### ISSUE TITLE
[Feature Request] Dynamic motd items

### ISSUE THREAD

**Issue by Lmmb74** [Derkades/ServerSelectorX#15]
Would you mind adding an option to change the item/item color depending on the motd the server is showing (Just like it does when the server is offline)? I think it is an interesting feature since it would be useful for minigames selection menus.

**Comment by Derkades** [comment]
I could definitely make that, what would the config look like? Something like this?
```
item-lore:
    1:
        text: "Example"
        item: STONE
        data: 0
    2:
        text:
        ....
```

**Comment by Lmmb74** [comment]
That is depending on the player count (Which would be great too :D), but I was thinking something more like:
```
motd-change:
    "MOTD-1":
        text: "Example"
        item: STONE
        data: 0
    "MOTD-2":
        text:
        ....
```
